import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/globals.css"
import Navbar from "../components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="p-3 justify-center  ">
          <Navbar/>
        </div>
      </body>
    </html>
  );
}
